[package]
authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "appledb_cli"
repository.workspace = true
version.workspace = true

[dependencies]
anyhow = "1.0.95"
apple-codesign = { version = "0.29.0", default-features = false }
appledb_common = { path = "../common" }
base64 = "0.22.1"
clap = { version = "4.5.29", features = ["derive"] }
env_logger = "0.11.6"
log = "0.4.25"
plist = { version = "1.7.0", features = ["serde"] }
reqwest = { version = "0.12.12", features = ["gzip"] }
serde = "1.0.217"
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = ["rt", "fs", "rt-multi-thread"] }
walkdir = { version = "2.5.0" }
